name: Shikkoku
version: ${project.version}
main: pro.shikkoku.Shikkoku
depend: [ProtocolLib]
commands:
  namechange:
  resetname:
  playerdataremover:
permissions:
  shikkoku.namechange:
    default: false
